# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3807a0f0e618a36c30ca2726bf91f9ddf04ad4f6de6912dce5f0dfb8cd65d8aeb2ee2501cf0a946d0f4719b4aacfe9550dbda2a13776d6085386065c4feb133

test:
  secret_key_base: 145ca974b100bb98f01c6c16601c7f8f8ca24abed146e75a233e584fb13cbf16edc10e1b5f59fb50a2a505e57212b520bbdd65eac14bac5e8dfd41b881517301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
